### PR TITLE
features (gdal2)

### PR DESCRIPTION
**Pull request by ocefpaf**
Same https://github.com/conda-forge/gdal-feedstock/pull/13

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins I rebased this PR against your latest changes. Can you take a quick look to check if everything is in order?

**Comment by gillins** [comment]
Looks good to me...

**Comment by ocefpaf** [comment]
OK. I can confirm that using features we have to skip Python 3.5 on Windows. This is safe to merge as the previous commit was build all but `py35`.

**Comment by gillins** [comment]
What is wrong with Python 3.5 on Windows? If it is a build problem I'll see if I can fix it.

**Comment by ocefpaf** [comment]
> What is wrong with Python 3.5 on Windows? If it is a build problem I'll
see if I can fix it.

I am on my phone now and I cannot copy and paste the error here. (Let me
know if you have access to AppVeyor's logs, if not I will copy the error
here tomorrow.)

Not sure how to fix it.  Many libraries are broken on Windows when we
activate features due to the compiler used. In fact, without features, we
where probably shipping a broken library. @msarahan
<https://github.com/msarahan> can comment more on this.

**Comment by msarahan** [comment]
This article sums up why it is bad to use one GDAL built with one MSVC with
a python built with a different MSVC:
http://siomsystems.com/mixing-visual-studio-versions/

**Comment by gillins** [comment]
OK I'll have a look later in the week and see if I can work out what is happening.

**Comment by ocefpaf** [comment]
Thanks for looking into this @gillins. Here is the error for future reference:

```shell
	link /nologo /dll /INCLUDE:_OGRFeatureStylePuller  /INCLUDE:_OSRValidate  /INCLUDE:_OPTGetProjectionMethods  /INCLUDE:_OGR_G_GetPointCount  /INCLUDE:_OGRRegisterAll /INCLUDE:_GDALSimpleImageWarp@36  /INCLUDE:_GDALReprojectImage@48  /INCLUDE:_GDALComputeMedianCutPCT@32  /INCLUDE:_GDALDitherRGB2PCT@28  /INCLUDE:_OCTNewCoordinateTransformation@8  port\*.obj gcore\*.obj alg\*.obj frmts\o\*.obj ogr\ogrsf_frmts\ogrsf_frmts.lib ogr\ogr.lib    C:\conda\envs\_build\Library\lib\xerces-c_3.lib            C:\conda\envs\_build\Library\lib\netcdf.lib    C:\conda\envs\_build\Library\lib\libtiff_i.lib     C:\conda\envs\_build\Library\lib\geos_c.lib C:\conda\envs\_build\Library\lib\hdf5.lib C:\conda\envs\_build\Library\lib\libkea.lib           odbc32.lib odbccp32.lib user32.lib  C:\conda\envs\_build\Library\lib\libpng.lib                   ws2_32.lib gcore\Version.res  /out:gdal200.dll /implib:gdal_i.lib   
   Creating library gdal_i.lib and object gdal_i.exp
odbccp32.lib(dllload.obj) : error LNK2019: unresolved external symbol __vsnwprintf_s referenced in function _StringCchPrintfW
gdal200.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.EXE"' : return code '0x460'
Stop.
 
C:\conda\conda-bld\work\gdal-2.0.2>if errorlevel 1 exit 1 
Command failed: C:\windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Pull request merged**
