### PR TITLE
ran conda-smithy regenerate

### PR DESCRIPTION
**Pull request by gillins**
Sorry, I meant to do this as part of #29 . Should explain why no Python 35 versions of GDAL got built.

### CODE REVIEW

**Comment by pelson** [comment]
Curious that numpy 1.9 has stuck around. Would you mind updating your version of conda-smithy? I've just released v0.8.4.

Thanks

**Comment by ocefpaf** [comment]
If we add `xz` (`libzma`) `fiona` will complain about a mismatch version... Maybe I should just give up `libxml2` support. (I am experimenting here locally and I will get back to you.)

**Comment by ocefpaf** [comment]
I've done this a several time too. Maybe we could add a message [here](https://github.com/conda-forge/gdal-feedstock/pull/31#issuecomment-206692745) to remind us to re-render.

**Comment by gillins** [comment]
That seemed to fix it. Hopefully I'll remember next time.

**Comment by pelson** [comment]
AppVeyor got 95% of the way and was showing success. Decided to merge to unblock some of the other builds (GDAL is pretty big) 😉

**Comment by ocefpaf** [comment]
Well.. We did not get to see a PY35+Win64 build :wink: 

It sucks that we can't cancel/re-start Appveyor individual builds.

**Pull request merged**
