### PR TITLE
bump bn

### LINKED ISSUE #241: DLL load failed on Appveyor Windows
I have a project that is using astropy's [ci-helpers](https://github.com/astropy/ci-helpers) to build a conda environment on appveyor. Nothing has been changed by us in our build setup, but we are now getting a DLL load failed error message:

```
  File "c:\projects\satpy\satpy\writers\geotiff.py", line 30, in <module>
    from osgeo import gdal, osr
  File "C:\Python27_64\envs\test\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Python27_64\envs\test\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.
```

You can see the full job and environment here: https://ci.appveyor.com/project/pytroll/satpy/builds/20702760/job/x0mo4l3940ff4n9h?fullLog=true

As far as I can tell both libgdal, gdal, and kealib are all coming from conda-forge. Any other ideas to what has changed recently that would cause this?

### PR DESCRIPTION
**Pull request by ocefpaf**
We had to build number `0`, probably an oversight on my side, I moved the most recent builds to `broken` and I'm re-triggering them here.

Fixes #241 and #242

### CODE REVIEW

**Comment by gillins** [comment]
Sorry I haven't been doing much with Windows (or conda-forge) lately. I'll try and find some time to look into this more, but quickly checking the `libtiff` package on Windows it looks like `tiff.dll` and `tiff.lib` are now supplied. https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/set_bld_opts.bat#L61 should now read:
```
TIFF_LIB=%LIBRARY_LIB%\tiff.lib ^
```
I think....

**Comment by gillins** [comment]
Looks like `geotiff` also needs to be updated first - see https://github.com/conda-forge/geotiff-feedstock/blob/master/recipe/bld.bat#L13

**Comment by ocefpaf** [comment]
The `build_linux_c_compilergcccxx_compilergxx` failure here is odd b/c the build completed but hanged for >10 min after that.

```

TEST END: /home/conda/feedstock_root/build_artifacts/linux-64/gdal-2.3.2-py36heb36068_1001.tar.bz2
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/gdal-split_1543795949656/work  to  /home/conda/feedstock_root/build_artifacts/gdal-split_1543795949656/work_moved_gdal-split-2.3.2-h9e57566_1001_linux-64_main_build_loop
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /home/conda/feedstock_root/build_artifacts/linux-64/libgdal-2.3.2-h9e57566_1001.tar.bz2
anaconda upload /home/conda/feedstock_root/build_artifacts/linux-64/gdal-2.3.2-py27heb36068_1001.tar.bz2
anaconda upload /home/conda/feedstock_root/build_artifacts/linux-64/gdal-2.3.2-py37heb36068_1001.tar.bz2
anaconda upload /home/conda/feedstock_root/build_artifacts/linux-64/gdal-2.3.2-py36heb36068_1001.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
####################################################################################
Resource usage summary:

Total time: 0:59:42.0
CPU usage: sys=0:03:02.3, user=0:54:37.8
Maximum memory usage observed: 610.2M
Total disk usage observed (not including envs): 97.0M


####################################################################################
Source and build intermediates have been left in /home/conda/feedstock_root/build_artifacts.
There are currently 1 accumulated.
To remove them, you can run the ```conda build purge``` command
+ upload_package /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_c_compilergcccxx_compilergxx.yaml
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from /home/conda/feedstock_root/.ci_support/linux_c_compilergcccxx_compilergxx.yaml
Too long with no output (exceeded 10m0s)
```

I have no idea what is going on with Windows :-(

**Comment by ocefpaf** [comment]
And the failures are gone after a re-start !!!

**Comment by djhoese** [comment]
FYI it seems like this newest build can't be installed in existing environments that use other libraries that depend on hdf5. For example h5py and netcdf4. Here's what I get on a Windows VM when I try to install the exact version for the new build in a python 3.6 environment I get:

```
(appveyor_debug) C:\Users\User>conda install "gdal=2.3.2=py36h1d93c02_1001"
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal==2.3.2=py36h1d93c02_1001 -> libgdal==2.3.2=h4d69586_1001 -> hdf5[version='>=1.10.4,<1.10.5.0a0']
  - h5py
Use "conda info <package>" to see the dependencies for each package.
```

I'm guessing `h5py` needs a rebuild with a newer `hdf5`? Of course that also means netcdf4 needs to be rebuilt to. And possibly others. I tested this on a brand new environment built in appveyor and it also didn't install the new build.

**Comment by kmuehlbauer** [comment]
@djhoese The hdf5 pinning was set to 1.10.4 currently. Good chance, that some packages skipped a pinning without building packages for that version, but honestly I don't know for sure.

**Comment by djhoese** [comment]
Good news is that if I uninstall `h5py` and `netcdf4` on my Windows VM and update `gdal` then it successfully finds the newest build and can be successfully imported. Should I create issues/PRs for h5py and netcdf4?

**Comment by kmuehlbauer** [comment]
@djhoese `libnetcdf` is already on the new pinning, but the python bindings for netcdf and hdf5 are still on hdf5 1.10.3. PRs with version bump and rerendering would suffice I think.

**Pull request merged**
