### PR TITLE
Fix libgdal-pdf that fails to work

### PR DESCRIPTION
**Pull request by rouault**
due to poppler not being found when building libgdal-core

which causes the plugin to emit the following and not being functional:
```
Warning 1: Driver PDF declares DMD_OPENOPTIONLIST whereas its proxy doesn't declare it or with a different value
Warning 1: Driver PDF declares DCAP_OPEN whereas its proxy doesn't declare it or with a different value
Warning 1: Driver PDF declares DMD_SUBDATASETS whereas its proxy doesn't declare it or with a different value
Warning 1: Proxy driver PDF declares a pfnIdentify callback whereas the real driver does not.
Warning 1: Driver PDF declares a pfnOpen callback whereas its proxy doest not declare DCAP_OPEN
```

### CODE REVIEW

**Comment by akrherz** [comment]
poppler was one of the main things that drove #722.  Does poppler just need to be present at build time and not at run?

**Comment by akrherz** [comment]
> just at build time.

I believe adding it as a dep will cause it to be added as a run dep, unless we do some tricks.  Will research this more soon and hopefully I am wrong :)

**Comment by rouault** [comment]
> Technically it doesn't even need to be there. Just having -DHAVE_POPPLER in CXXFLAGS of libgdal-core should be enough

trying that approach in https://github.com/conda-forge/gdal-feedstock/pull/976

**Comment by xylar** [comment]
> I believe adding it as a dep will cause it to be added as a run dep, unless we do some tricks. 

I don't think so.  I didn't see any `run_exports`:
https://github.com/conda-forge/poppler-feedstock/blob/main/recipe/meta.yaml

**Comment by akrherz** [comment]
Can a simple test be added to the `libgdal-pdf` artifact section to ensure that it is working?

**Comment by rouault** [comment]
> Can a simple test be added to the `libgdal-pdf` artifact section to ensure that it is working?

attempted in #976 with 41f671383fa4ab65fdf7bc4fb66faaf0bf6ede0b

**Comment by rouault** [comment]
closing as superseded per #976

**Pull request closed without merging**
