### PR TITLE
Rebuild for PROJ 6.1.0

### PR DESCRIPTION
**Pull request by snowman2**
@conda-forge-admin, please rerender.

### CODE REVIEW

**Comment by snowman2** [comment]
Feel free to close if it is supposed to happen in the pins repo.

**Comment by ocefpaf** [comment]
> Feel free to close if it is supposed to happen in the pins repo.

Proj4 is pinning to the exact version (`x.x.x`) so we need to change that in the global pinning. If you want to test it here it is fair game to add `6.1.0` in the `meta.yaml`. Note that we are pinning everything else to `gdal 2.4` b/c of `rasterio` and `fiona`, so this will only be used in case users are installing `gdal` alone in an environment.

**Comment by snowman2** [comment]
I think changing the global pinning is the way to go. Thanks!

**Comment by ocefpaf** [comment]
> I think changing the global pinning is the way to go. Thanks!

I just sent a PR for a migration to proj4 6.1.0. Let's close this one and wait for the bot!

**Comment by snowman2** [comment]
👍

**Pull request closed without merging**
