### PR TITLE
add libkml support on Windows

### LINKED ISSUE #507: Enabling LibKML Driver on Windows
- [x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: This is related to [Enabling LibKML Driver #152](https://github.com/conda-forge/gdal-feedstock/issues/152), which is closed. The [Linux & Max builds](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/build.sh#L47) have the libkml driver enabled, but the [Windows build](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/set_bld_opts.bat) does not (also indicated in the [comments here](https://github.com/conda-forge/libgdal-feedstock/pull/3)).

Could the libkml driver be added to the Windows conda-forge gdal package?

<br/>
Environment (<code>conda list</code>):

```
python --version
Python 3.7.10

gdalinfo --version
GDAL 3.3.1, released 2021/06/28
```
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
conda 4.10.3

```
</details>

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #507

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@ocefpaf any idea why it won't grab the latest `libkml`?

**Comment by ocefpaf** [comment]
> @ocefpaf any idea why it won't grab the latest `libkml`?

They are all the same version and the solver does not optimize for build number :-(

@wolfv mambabuild would optimize the build number, right? If so I'd like to try it here to make a case for a change in our CI config :grimacing:

**Comment by ocefpaf** [comment]
@gillins if my attempt to use mambabuild does not work the only way would be to remove the previous versions from the channel. We can mark all 1014 as broken on Windows.

**Comment by gillins** [comment]
@ocefpaf whatever you did worked! Well done. Are you happy to merge?

> We can mark all 1014 as broken on Windows.

It's actually 1013 that is broken on Windows. I guess users would still get the old `libkml`, but not that this matters as it as a static lib ATM (seems next version will allow shared lib on Windows https://github.com/libkml/libkml/commit/e00df3487022bf64b3bde2367dbf7516e4fcab9b#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a)

**Comment by ocefpaf** [comment]
> @ocefpaf whatever you did worked! Well done. Are you happy to merge?

I only restarted the build :smile: Hopefully it was only a CDN sync issue and the latest package was not available in the previous run.

> It's actually 1013 that is broken on Windows. I

I guess we should remove it then, right? I'll do it tomorrow.

**Comment by gillins** [comment]
Thanks @ocefpaf ! Yeah probably won't hurt to remove 1013 - whatever you think.

**Comment by asarmy** [comment]
@gillins or @ocefpaf Thanks for adding this feature! 

Newbie here, what is the best way to update gdal on my end? Using Windows and Anaconda. Should I run `conda upgrade gdal` in Anaconda prompt? or just re-run `conda install -c conda-forge gdal`?

**Comment by ocefpaf** [comment]
It depends on your workflow. Ideally we recommend to use environments and a new one would get you this feature. Updating existing ones can be a hit and miss b/c the solver will try to optimize to the installed packages you have there.

**Pull request merged**
