### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #253.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

### CODE REVIEW

**Comment by hobu** [comment]
Unfortunately this is now failing on OSX with the following:

```
old_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libxml2.la: No such file or directory
hold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libxml2.la: No such file or directory
libtool:   error: '/Users/distiller/miniconda3/conda-bld/gdal-d_placehold_place/lib/libxml2.la' is not a valid libtool archive
```

**Comment by kmuehlbauer** [comment]
@hobu I checked with the gitter-channel. Let's try this recommended fix.

**Comment by kmuehlbauer** [comment]
Just to not forget, we need to bump the build number before merge!

**Comment by kmuehlbauer** [comment]
@isuruf Thanks! The `find $PREFIX/lib -name '*.la' -delete` did work! Could you elaborate a bit why that happened and if there is some documentation about it?

**Comment by isuruf** [comment]
We started deleting .la files from packages and then conda-build started deleting .la files as well. But some old packages still have the .la packages. If B's .la depends on A's .la and when A is packaged .la file is deleted, but an old version of B is still used, then B's .la can't find A's .la. Solution is to delete all the .la files at the beginning

**Pull request merged**
