### PR TITLE
rebuild for proj810

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

closes #538

### CODE REVIEW

**Comment by akrherz** [comment]
#533 did 3.2 branch
#532 failed at 3.1 branch

**Comment by xylar** [comment]
Yes, this is odd.  Hopefully it's just a bot glitch. Thanks for doing the manual migration.

**Comment by akrherz** [comment]
This PR appears to be in good shape, verified that the successful linux64 build picked up `proj=8.1.0`  automerge? :)

**Comment by xylar** [comment]
It looks like it's not working yet on `ppc` -- solver issues.  I have access to a ppc system that I might be able to use to debug this, but not sure when I'll have time.  Or we could retry in the hopes that some dependency was just taking ages to build and update, and might be there when we re-run?

**Comment by akrherz** [comment]
dig dig dig, argh, [libspatialite master build on ppc failed](https://app.travis-ci.com/github/conda-forge/libspatialite-feedstock/builds/238288549), restarting Travis-CI....  Rewording, no libspatialite + proj8.1 on ppc at the moment.

**Comment by xylar** [comment]
Oh, good catch!

**Comment by akrherz** [comment]
Augh, restarted Travis-CI libspatialite build for the fourth time, continues to hang at various conda steps for unknown reasons....

**Comment by xylar** [comment]
Maybe let it be for now, and try again tomorrow.  I'm guessing Travis is just overwhelmed at the moment.

**Comment by akrherz** [comment]
Tried restarting libspatialite today a couple of times, more stales.  Will ask on gitter and see if anybody there knows what is up

**Comment by xylar** [comment]
I pushed a [dummy commit](https://github.com/conda-forge/libspatialite-feedstock/commit/79d97d00e6430456c5ca2808da73dbcae2d2378f) but Travis is still not behaving.  @akrherz, did you post on gitter?  I didn't see a discussion.

**Comment by akrherz** [comment]
> @akrherz, did you post on gitter? I didn't see a discussion.

Yes, I am in the POWER channel

**Comment by xylar** [comment]
Ah, got it!

**Comment by xylar** [comment]
It doesn't look like the conda-forge on POWER channel gets much traffic.  I'd try again on https://gitter.im/conda-forge/conda-forge.github.io

**Comment by akrherz** [comment]
It'd be nice to temporarily modify the conda command to use `travis_wait`, what do you think of that idea?

**Comment by akrherz** [comment]
conda-forge/libspatialite-feedstock#75 has been merged, awaiting build upload and metadata regeneration before restarting CI here.  Excitement is building fast at least!

**Comment by akrherz** [comment]
Looks like we are ready, fingers crossed
```
$ curl -s https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json | jq .packages'["libspatialite-5.0.1-h942b99a_8.tar.bz2"]'
{
  "build": "h942b99a_8",
  "build_number": 8,
  "depends": [
    "freexl >=1.0.6,<2.0a0",
    "geos >=3.9.1,<3.9.2.0a0",
    "libgcc-ng >=9.4.0",
    "librttopo >=1.1.0,<1.2.0a0",
    "libstdcxx-ng >=9.4.0",
    "libxml2 >=2.9.12,<2.10.0a0",
    "proj >=8.1.0,<8.1.1.0a0",
    "sqlite >=3.36.0,<4.0a0",
    "zlib >=1.2.11,<1.3.0a0"
  ],
  "license": "MPL-1.1",
  "md5": "91eeebbce46073d9c07ac3d35fd7b4e7",
  "name": "libspatialite",
  "sha256": "7ba2ab16b8120dc8d70149670de886ab4ae7181fb0195380470480e05c6ff371",
  "size": 4324061,
  "subdir": "linux-ppc64le",
  "timestamp": 1632757689101,
  "version": "5.0.1"
}
```

@conda-forge-admin, please restart ci

**Comment by akrherz** [comment]
:cry: geotiff is a problem now, researching

```
Package proj conflicts for:
libspatialite -> proj[version='>=8.0.0,<8.0.1.0a0|>=8.0.1,<8.0.2.0a0|>=8.1.0,<8.1.1.0a0']
proj=8.1.0
geotiff=1.7 -> proj[version='>=6.2.1,<6.2.2.0a0|>=8.0.1,<8.0.2.0a0']
```

**Comment by xylar** [comment]
@akrherz, let us know what you find out.  If you get stuck, I can try to see what I can find out this evening.  Nothing super obvious -- geotiff 1.7 was rebuilt for proj 8.1.0 as you have surely seen, so it must be dependencies of dependencies.

**Comment by akrherz** [comment]
> let us know what you find out.

Same problem as with libspatialite, the [Travis-CI build failed](https://app.travis-ci.com/github/conda-forge/geotiff-feedstock/builds/235092804) on master after the proj81 merge :(  conda-forge/geotiff-feedstock#40 now made with same cross build change

**Comment by xylar** [comment]
The `geotiff` package should now be ready.  My suggestion would be to wait until the `aarch64` build has finished, since it seems to be working.  Then, we can just restart the one failed build rather than restarting everything.  Is that okay with you @akrherz?

**Comment by akrherz** [comment]
Note that I don't have perms I think to restart Azure jobs and to confirm that I now see the geotiff ppc64le build now available
```
$ curl -s https://conda.anaconda.org/conda-forge/linux-ppc64le/repodata.json | jq .packages'["geotiff-1.7.0-h1bc9efb_2.tar.bz2"]'
{
  "build": "h1bc9efb_2",
  "build_number": 2,
  "depends": [
    "jpeg >=9d,<10a",
    "libgcc-ng >=9.4.0",
    "libstdcxx-ng >=9.4.0",
    "libtiff >=4.3.0,<5.0a0",
    "proj >=8.1.0,<8.1.1.0a0",
    "zlib >=1.2.11,<1.3.0a0"
  ],
  "license": "MIT",
  "md5": "c9d4fc30849ae843a391d09423181164",
  "name": "geotiff",
  "sha256": "dd5e20d443ca53cb18479ba33299047473f279d5e9f7fc517f128fd74451124e",
  "size": 326546,
  "subdir": "linux-ppc64le",
  "timestamp": 1632769961866,
  "version": "1.7.0"
}
```

**Comment by xylar** [comment]
If you go to "Details", you should see "re-run" next to the failed Azure jobs, but it won't do anything until all jobs have either succeeded or failed.  I'll give it a go as soon as `aarch64` has passed.  (If it fails, we should just restart everything.)

**Comment by xylar** [comment]
And after all that the `aarch64` job took too long and hit the 6-hour limit.  Starting over...

**Pull request closed without merging**
