### PR TITLE
create intermediate build for qt compatability

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* :heavy_minus_sign:  [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

see #585 

This is an attempt to create an intermediate build of gdal 3.4.0 with a combination of dependencies that should play nice with the most recent build of `qt`.  As an initial sanity test, this resolves within mamba.

$ mamba create -n dev python=3.10 libpq=13.1 icu=68 expat=2.2 qt

I purposefully did not rerender here.  We will want to:

- [x] carefully inspect the CI reported build dependencies to see if my hard coding here worked.

Credit for this suggestion goes to @xylar, thanks!  Blame for code execution and subsequent breakages goes to me!

### CODE REVIEW

**Comment by akrherz** [comment]
Well, that quickly went up in dependency flames

```
   Encountered problems while solving:
     - nothing provides libcurl 7.79.0 h2574ce0_0 needed by curl-7.79.0-hea6ffbf_0
```

and debugging another step

```
$ mamba create -n dev python=3.10 libpq=13.1 icu=68 expat=2.2 qt libcurl=7.79
- package libcurl-7.79.1-h2574ce0_0 requires krb5 >=1.19.2,<1.20.0a0
```

Ah, libpq=13.1 is too tight and not necessary.  Attempt 2 ahoy...

**Comment by akrherz** [comment]
Hmmm again

openssl1 build
```
   Encountered problems while solving:
     - nothing provides requested openssl 1.1.1
```

openssl3 build
```
   Encountered problems while solving:
     - package libpq-13.1-hfd2b0eb_0 requires openssl >=1.1.1i,<1.1.2a
```

:cry: there is no libpq=13 + openssl3 build, but that does not explain the openssl=1 failure....

**Comment by akrherz** [comment]
The [postgresql 13.5 release notes](https://www.postgresql.org/docs/release/13.5/) indicate openssl3 support was added with that point release, so I suppose I could submit a PR there :)

**Comment by xylar** [comment]
@akrherz, I did a local build with openssl1 on linux-64 and everything worked fine.  I don't understand why `mamba` is having trouble in CI but not when I try building.  Going to see if restarting CI happens to help.

**Comment by xylar** [comment]
BTW, I don't think editing the files in `.ci_support` is the "right" way to do this.  Instead, we would probably want to specify versions that differ from the pins in the `meta.yaml` (both in host and run).  We could use a `recipe/conda_build_config.yaml` in cases were we need to specify a matrix.

**Comment by xylar** [comment]
Hmm, obviously the solver issue is persistent.  But I can't reproduce it locally so I don't think I can help further at least for now.

**Comment by xylar** [comment]
I wouldn't worry about openssl3 for now.  We could just remove it for this build.

**Comment by akrherz** [comment]
Thanks again @xylar , what do you think of the latest commit?

**Comment by xylar** [comment]
@akrherz, it looks like a good approach!  I think you may still need a constraint on `expat` but I could be wrong.

**Comment by akrherz** [comment]
> I think you may still need a constraint on `expat`

You think it needs to be `>=2.2,<2.4` or ?

**Comment by xylar** [comment]
Hmm, maybe let it be for now.  What I'm seeing is:

```
$ mamba search --info qt
...
  - expat >=2.2.10,<3.0.0a0
...

$ mamba search --info libgdal=3.4.0
...
   - expat >=2.4.1,<3.0a0
...
```
Those should be compatible.  The pin for `qt` is `expat=2.2`, but I guess that gets rendered as `expat >=2.2,<3`?

**Comment by xylar** [comment]
In terms of debugging the solver issue, I don't have a better suggestion at this point than to just start commenting out dependencies and rerendering until the that initial host solve works.

**Comment by xylar** [comment]
If you have docker installed locally and can reproduce the issue, that would likely be much faster than doing it here.

**Comment by akrherz** [comment]
> If you have docker installed locally and can reproduce the issue, that would likely be much faster than doing it here.

I am having trouble getting it to work with podman :(  I am reproducing the dep issue though.

**Comment by akrherz** [comment]
And gasp, changing "openssl=1.1.1" to "openssl=1.1.1l"  and mamba works :(

**Comment by xylar** [comment]
> And gasp, changing "openssl=1.1.1" to "openssl=1.1.1l" and mamba works :(

Interesting.  I think the conda solver (and maybe also the mamba solver) has problems sometimes with deciding whether a given version number is legit or a release candidate that it should ignore.  This might be such a situation.

**Comment by xylar** [comment]
Maybe use the pin that `gdal` was rendering with:
```
'openssl >=1.1.1l,<1.1.2a'
```

**Comment by akrherz** [comment]
So my understanding is that not having a `openssl=3` build here is not of concern for the `qt` compatibility as `qt` has a direct openssl requirement and was not migrated yet.  So feedstocks with an openssl3 requirement + qt are stuck anyway, irregardless of gdal.  This change should help feedstocks that have no-openssl requirement, but have a qt + gdal requirement.  I do surely hope.

Anxiously awaiting to review build output requirements output :)

**Comment by akrherz** [comment]
Well, the reported recipes at the end of the build neither report icu nor libpq, sigh.  From my reading of the build and compile logs, I believe this did what we intended...

**Review by xylar — APPROVED** [review]
I'm good with this as long as there's a PR waiting in the wings to reverse these changes and bump to build 12.

**Comment by akrherz** [comment]
> I'm good with this as long as there's a PR waiting in the wings to reverse these changes and bump to build 12.

Thanks, Will do!

**Pull request merged**
