### PR TITLE
WIP: Back-port PR #17

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @gillins I added you as a maintainer here too.

PS: @kmuehlbauer and @gillins I am planning to put `gdal2` into master and start a `gdal 1.x series` branch as soon as the new `fiona` (that will work with `gdal` 2) is released.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I get the error below when using `libxml2` on OS X. Adding `libtool` and `libiconv` does not solve the issue. It seems similar to what I see in https://github.com/conda-forge/staged-recipes/pull/257.

```shell
/bin/sh /Users/travis/miniconda3/conda-bld/work/gdal-1.11.4/libtool --mode=link	g++ -L/Users/travis/miniconda3/envs/_build/lib   -L/Users/travis/miniconda3/envs/_build/lib -lproj -ljson-c -L/Users/travis/miniconda3/envs/_build/lib -L/Users/travis/miniconda3/envs/_build/lib -lfreexl -L/Users/travis/miniconda3/envs/_build/lib -lgeos_c  -lsqlite3 -L/Users/travis/miniconda3/envs/_build/lib -lexpat -L/Users/travis/miniconda3/envs/_build/lib -lxerces-c -lpthread -L/Users/travis/miniconda3/envs/_build/lib -lopenjp2 -ljasper -L/Users/travis/miniconda3/envs/_build/lib -lnetcdf -L/Users/travis/miniconda3/envs/_build/lib -lhdf5  -L/Users/travis/miniconda3/envs/_build/lib -lmfhdf -ldf -lgif -L/Users/travis/miniconda3/envs/_build -L/Users/travis/miniconda3/envs/_build/lib -ljpeg -L/Users/travis/miniconda3/envs/_build/lib -ltiff -L/Users/travis/miniconda3/envs/_build -L/Users/travis/miniconda3/envs/_build/lib -lpng -lz -L/Users/travis/miniconda3/envs/_build -L/Users/travis/miniconda3/envs/_build/lib -lpthread -ldl    -L/Users/travis/miniconda3/envs/_build/lib -lcurl -lssl -lcrypto -lz             -L/Users/travis/miniconda3/envs/_build/lib -lxml2 -lz -liconv -lm  -o libgdal.la /Users/travis/miniconda3/conda-bld/work/gdal-1.11.4/frmts/o/*.lo /Users/travis/miniconda3/conda-bld/work/gdal-1.11.4/gcore/*.lo /Users/travis/miniconda3/conda-bld/work/gdal-1.11.4/port/*.lo /Users/travis/miniconda3/conda-bld/work/gdal-1.11.4/alg/*.lo /Users/travis/miniconda3/conda-bld/work/gdal-1.11.4/ogr/ogrsf_frmts/o/*.lo ./ogr/ogrgeometryfactory.lo ./ogr/ogrpoint.lo ./ogr/ogrcurve.lo ./ogr/ogrlinestring.lo ./ogr/ogrlinearring.lo ./ogr/ogrpolygon.lo ./ogr/ogrutils.lo ./ogr/ogrgeometry.lo ./ogr/ogrgeometrycollection.lo ./ogr/ogrmultipolygon.lo ./ogr/ogrsurface.lo ./ogr/ogrmultipoint.lo ./ogr/ogrmultilinestring.lo ./ogr/ogr_api.lo ./ogr/ogrfeature.lo ./ogr/ogrfeaturedefn.lo ./ogr/ogrfeaturequery.lo ./ogr/ogrfeaturestyle.lo ./ogr/ogrfielddefn.lo ./ogr/ogrspatialreference.lo ./ogr/ogr_srsnode.lo ./ogr/ogr_srs_proj4.lo ./ogr/ogr_fromepsg.lo ./ogr/ogrct.lo ./ogr/ogr_opt.lo ./ogr/ogr_srs_esri.lo ./ogr/ogr_srs_pci.lo ./ogr/ogr_srs_usgs.lo ./ogr/ogr_srs_dict.lo ./ogr/ogr_srs_panorama.lo ./ogr/ogr_srs_ozi.lo ./ogr/ogr_srs_erm.lo ./ogr/swq.lo ./ogr/swq_expr_node.lo ./ogr/swq_parser.lo ./ogr/swq_select.lo ./ogr/swq_op_registrar.lo ./ogr/swq_op_general.lo ./ogr/ogr_srs_validate.lo ./ogr/ogr_srs_xml.lo ./ogr/ograssemblepolygon.lo ./ogr/ogr2gmlgeometry.lo ./ogr/gml2ogrgeometry.lo ./ogr/ogr_expat.lo ./ogr/ogrpgeogeometry.lo ./ogr/ogrgeomediageometry.lo ./ogr/ogr_geocoding.lo ./ogr/osr_cs_wkt.lo ./ogr/osr_cs_wkt_parser.lo ./ogr/ogrgeomfielddefn.lo \

	    -rpath /Users/travis/miniconda3/envs/_build/lib \

	    -no-undefined \

	    -version-info 19:4:18

grep: /usr/lib/libiconv.la: No such file or directory

sed: /usr/lib/libiconv.la: No such file or directory

libtool: link: `/usr/lib/libiconv.la' is not a valid libtool archive

make[1]: *** [libgdal.la] Error 1

make: *** [check-lib] Error 2

Command failed: /bin/bash -x -e /Users/travis/build/conda-forge/gdal-feedstock/recipe/build.sh
```

**Comment by gillins** [comment]
Sounds like a good plan. Are you planning to update bld.bat also? FYI it seems latest HDF breaks GDAL on Windows #25 . Is anyone else testing under Windows?

I'm hoping to submit another PR with a tidy up of the Windows build and better test script after I've worked out what is going on with HDF5.

**Comment by kmuehlbauer** [comment]
Good news, that things are evolving. Also, GDAL maintainers announced gdal 2.1 release candidate the day before. So gdal 2.1 will hit surface in a week. I've no idea if there will be a 1.11.X iteration.

**Comment by kmuehlbauer** [comment]
@gillins I can test on Windows later today or tomorrow. What specific things should I look for?

**Comment by gillins** [comment]
That would be great! Let me know what you find.
I'm getting some linking errors (see #25) but it is fine with older HDF5 (1.8.15). I also hope to have another look in the next 24 hours or so.

**Comment by kmuehlbauer** [comment]
@gillins, AFAIK libnetcdf4 is compiled against hdf 1.8.15 headers, but the latest hdf is already 1.8.16. Is it possible

**Comment by gillins** [comment]
Ah - this indeed could be the problem! Good thought.

**Comment by kmuehlbauer** [comment]
There is conda-forge/staged-recipes#213 to get a conda forge libnetcdf. Maybe you can also have a look there, to get this in soon. I didn't had time so far.

**Comment by ocefpaf** [comment]
> Sounds like a good plan. Are you planning to update bld.bat also? FYI it seems latest HDF breaks GDAL on Windows #25 . Is anyone else testing under Windows?

Missed that! Doing it now.

**Comment by ocefpaf** [comment]
Before we merge this:

- [ ] solve what is going on with `libxml2` on OS X
- [ ] sort libspatialite (probably same issue above)
- [ ] sort netcdf out (see https://github.com/conda-forge/staged-recipes/pull/213)

After that we can sync with #26 and switch branches.

**Comment by ocefpaf** [comment]
@jakirkham `libxml2` installs `icu`, but something is amiss...

```
import: 'osr'
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import osr
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/osr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: dlopen(/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/osgeo/_gdal.so, 2): Library not loaded: ../lib/libicudata.56.1.dylib
  Referenced from: /Users/travis/miniconda3/envs/_test/lib/libgdal.1.dylib
  Reason: image not found
TESTS FAILED: gdal-1.11.4-np110py34_3
```

**Comment by ocefpaf** [comment]
I am not using `libxml2` and `libspatialite` on OS X because of https://github.com/conda-forge/gdal-feedstock/pull/27#issuecomment-205920818

**Comment by jakirkham** [comment]
So, I thought `libxml2` shouldn't have this issue any more. However, `libspatialite` may still have it if it linked to `libxml2`.

**Comment by jakirkham** [comment]
Also, did you run `conda inspect`? I would be curious what `libgdal.1.dylib` is linked against.

**Comment by jakirkham** [comment]
@gillins, yes, there is a mixture of HDF5 version support in the stack here. We need to fix everything to use the new version and then we should be good.

**Comment by ocefpaf** [comment]
> Also, did you run `conda inspect`? I would be curious what libgdal.1.dylib is linked against.

`conda inspect` does not work on Travis-CI because we are using latest conda-build there and versions >1.18.2 have [this](https://github.com/conda/conda-build/issues/836) bug. (And I don't have a Mac to test it.)

**Comment by ocefpaf** [comment]
> libspatialite may still have it if it linked to libxml2.

So we need a similar for `libspatialite`? That is unfortunate that `libspatialite` did not catch anything.

**Comment by jakirkham** [comment]
No. :smile: I think I just found the really problem and a fix. :fireworks:

**Comment by ocefpaf** [comment]
> No. :smile: I think I just found the real problem and a fix. :fireworks:

Awesome!

**Pull request merged**
