### PR TITLE
Cross compile linux aarch and ppc on linux 64

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

~~I have no idea if I done this right, but the rerender seems to have done what I thought was needed?  I throw myself at the benevolence of the conda-forge experts to kindly educate me if this is the wrong approach...~~

PR morphed into cross compiling aarch and ppc on linux 64 to gain ~5-6x speedup.

### CODE REVIEW

**Comment by xylar** [comment]
@akrherz, each of these builds will produce a redundant `libgdal` with the same hash.  Isn't that going to be dangerous?

**Comment by xylar** [comment]
@ocefpaf, what do you think about this approach?  Is there someone else from core we should check with?

**Comment by akrherz** [comment]
> Isn't that going to be dangerous?

Yes, we would not want that.  I was blinding thrashing here and am researching this more now.  Here's what I see from the linux x64 build that finished

Label | gdal | libgdal
--- | --- | ---
linux linux_64_numpy1.18python3.7.____cpython | gdal-3.4.0-py37h7b489ff_2 | libgdal-3.4.0-hc0e84f1_2
linux linux_64_numpy1.18python3.8.____cpython |gdal-3.4.0-py38hcf2042a_2 | libgdal-3.4.0-hc0e84f1_2
linux linux_64_numpy1.19python3.9.____cpython | gdal-3.4.0-py39h0494519_2 | libgdal-3.4.0-hc0e84f1_2
linux linux_64_numpy1.21python3.10.____cpython | gdal-3.4.0-py310h222ae0d_2 | libgdal-3.4.0-hc0e84f1_2

**Comment by xylar** [comment]
It's good that all the redundant `libgdal` builds have the same hash but we would need to somehow designate only one of the jobs to do the actual upload.  I don't know if that's possible.

**Comment by akrherz** [comment]
@xylar what about a `skip` on the outputs for anything other than python 3.10 ?  Too brittle?

**Comment by xylar** [comment]
@akrherz, that unfortunately won't work because each `gdal` build requires the associated `libgdal` build.  My suggestion from earlier was that we unarchive the `libgdal` feedstock and only build the `gdal` packages here.  That would be similar to how `esmf` and `esmpy` works.

**Comment by ocefpaf** [comment]
> @akrherz, that unfortunately won't work because each `gdal` build requires the associated `libgdal` build. My suggestion from earlier was that we unarchive the `libgdal` feedstock and only build the `gdal` packages here. That would be similar to how `esmf` and `esmpy` works.

I'm not a big fan of that but at this point you two are more capable of deciding the future of this feedstock than me :-)

If you believe that will help we will need to adjust the dependency graph, to get the bot to work properly, and unarchive libgdal.

**Comment by akrherz** [comment]
well, nothing is being saved on the build times here :sob:

**Comment by xylar** [comment]
> well, nothing is being saved on the build times here sob

I think the problem is that building `libgdal` takes 96% of the time and building the 4 python packages takes the remaining 4 percent.  These are probably exaggerations but the point is that `libgdal` could take the full 6 hours on its own.  In which case we haven't won anything significant by splitting up the package. 

@ocefpaf, thanks for the input.  I don't think there's good evidence that we want to go that route and your arguments for not doing so are convincing.

Are there any options for requesting longer azure timeouts for this package?

**Comment by akrherz** [comment]
Has anybody tried cross compiling to see how slow that is?  I have redid this PR to do that now to see how badly it goes up in flames.

**Comment by xylar** [comment]
> Has anybody tried cross compiling to see how slow that is?

I'm not quite sure how things work on Azure.  I think it might always be cross-compiling but I haven't seen a clear explanation.  In any case, everything seems about equally slow either way.  It would be hard for me to imaging that cross-compiling would speed things up.

**Comment by akrherz** [comment]
@xylar It appears to be 5-6x faster, augh, sigh, horray?

**Comment by xylar** [comment]
@akrherz, hmm, that's interesting!

**Comment by xylar** [comment]
@akrherz, well, I was clearly wrong.  I'm glad to know this for future reference!

Do you want to rename this PR and update the description so we can merged it?  And probably make the same change for `3.3.x`?

**Comment by akrherz** [comment]
@xylar done and done and done.

**Comment by xylar** [comment]
Crazy, I can hardly believe it!

**Pull request merged**
