### PR TITLE
Add license information to outputs

### PR DESCRIPTION
**Pull request by Hofer-Julian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
@conda-forge-admin, please rerender

**Comment by Hofer-Julian** [comment]
Mmmmh, I've hoped that this would fix the missing license [here](https://anaconda.org/conda-forge/libgdal) and here: https://github.com/conda-forge/gdal-feedstock/blob/1af2211a0d3004212a90cdebbdf13b4798bd0d2b/README.md?plain=1#L6

**Comment by zklaus** [comment]
Good catch about the missing license information, @Hofer-Julian. I don't think we need to add a copy of the file since it is included in the source archive.

Perhaps we need to add the license information to the `about` sections of the outputs?

**Comment by Hofer-Julian** [comment]
>  I don't think we need to add a copy of the file since it is included in the source archive.

As far as I can tell adding the license file is required, there is even a checkbox in the PR template for that.
Maybe there is a way around that though.

> Perhaps we need to add the license information to the about sections of the outputs?

That might be, the other packages with missing licenses I've found also produced multiple packages per feedstock ([gstreamer ](https://github.com/conda-forge/gstreamer-feedstock) and [postgresql](https://github.com/conda-forge/postgresql-feedstock)).

**Comment by Hofer-Julian** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
> > I don't think we need to add a copy of the file since it is included in the source archive.
> 
> As far as I can tell adding the license file is required, there is even a checkbox in the PR template for that. Maybe there is a way around that though.

This is a common notion, but I believe it is a misconception, see https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually.

If there is contradictory information, it would be good to straighten this out, I guess.

**Comment by Hofer-Julian** [comment]
> Perhaps we need to add the license information to the about sections of the outputs?

That worked, good catch!

> This is a common notion, but I believe it is a misconception, see https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually.

I see, I've removed the license file

**Comment by zklaus** [comment]
Thinking about this, this raises the question of whether the same license applies to both outputs. Did you check that?

**Comment by Hofer-Julian** [comment]
> Thinking about this, this raises the question of whether the same license applies to both outputs. Did you check that?

I would say yes. They are distributed together and as far as I can tell there is only one LICENSE.
Do you have differing information?

**Comment by zklaus** [comment]
> 

I'm happy with that.

**Review by zklaus — APPROVED** [review]

**Comment by djhoese** [comment]
I'm working on a reproducer for this, but it seems this latest build has somehow broken importing rasterio. I'll make an issue if I can figure it out. I understand that this is just a license PR, but something changed.

```
   File "/Users/runner/miniconda3/envs/test-environment/lib/python3.10/site-packages/trollimage/xrimage.py", line 58, in <module>
    from rasterio.windows import Window
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.10/site-packages/rasterio/__init__.py", line 11, in <module>
    with rasterio._loading.add_gdal_dll_directories():
AttributeError: partially initialized module 'rasterio' has no attribute '_loading' (most likely due to a circular import). Did you mean: 'logging'?
```

It may be OSX specific.

**Comment by djhoese** [comment]
Nevermind, it doesn't seem to be this PR, but rather people making commits directly to main:

https://github.com/conda-forge/gdal-feedstock/commits/main/recipe/meta.yaml

@zklaus @gillins What's going on? Is there an issue or PR tracking your changes?

**Comment by akrherz** [comment]
@djhoese The big cmake PR #629 went in.

**Comment by djhoese** [comment]
@akrherz Just saw that. The fact that github doesn't default to sorting PRs by recently updated still blows my mind. Thanks for pointing me in the right direction. I've made a comment there and am having coworkers run stuff on their Macs to confirm.

**Pull request merged**
