### PR TITLE
Rebuild python39 0 2 h58c898

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #415

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/gdal Ready for review

**Comment by kmuehlbauer** [comment]
@chrisburr Thanks for looking into this. While briefly sweeping through the build logs I didn't find anything suspiciuous. Let's wait for another set of :eyes:.

**Review by kmuehlbauer — APPROVED** [review]

**Comment by xylar** [comment]
Looks good to me.  Thanks for figuring this out @chrisburr!  I'm going to go ahead and merge.

**Comment by ocefpaf** [comment]
It feels my heart with glee to see 3 sets of hands on deck for this! Thanks @chrisburr, @kmuehlbauer, and @xylar!!!

**Pull request merged**
