### PR TITLE
Proj52

### PR DESCRIPTION
**Pull request by snowman2**
@conda-forge-admin please rerender.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Not sure what is going on with the Windows builds there but building packages with older versions is never easy :-/

**Comment by snowman2** [comment]
Yeah, the GDAL stack is especially fun 🙃. This is not a blocker at the moment, so I wouldn't loose any sleep over it. Thanks for updating the pins BTW.

**Comment by gillins** [comment]
I've seen this error before - not sure how it happens - but workaround is to remove the duplicate definition. Seems to work ok now.

**Comment by ocefpaf** [comment]
Awesome! Thanks @gillins!

**Comment by snowman2** [comment]
Nice, thanks @gillins!

**Pull request merged**
