### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@ocefpaf Can you please have a final look? This should fix issue #249 until the next version bumb of curl.

**Comment by ocefpaf** [comment]
> @ocefpaf Can you please have a final look? This should fix issue #249 until the next version bumb of curl.


While this PR is desirable b/c it adds the `geotiff` pinning this won't fix #249 b/c the curl pinning is unchanged. Please see 

https://github.com/conda-forge/gdal-feedstock/issues/249#issuecomment-448985552

for my long answer.

**Comment by kmuehlbauer** [comment]
@ocefpaf Thanks for the elaborate answer. Glad this PR is useful nonetheless.

**Pull request merged**
