### PR TITLE
update to 2.2.3

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins do you have an idea what may be wrong with the `XLS` driver? I am getting an error on `OS X`:

```
XLS
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/gdal_1511564121549/test_tmp/run_test.py", line 21, in <module>
    assert ogr.GetDriverByName(driver)
AssertionError
```

I did update `freexl`, but I've been trying combinations with older versions with no avail :-/

**Comment by gillins** [comment]
Hmmm seems `freexl` support failed to build in the latest [`libgdal` PR](https://github.com/conda-forge/libgdal-feedstock/pull/27) - see https://travis-ci.org/conda-forge/libgdal-feedstock/builds/306806136#L1560. Not sure why... I'll have a look when I get a moment. Maybe disable for now?

**Comment by gillins** [comment]
> I've been trying combinations with older versions with no avail :-/

Have you been rebuilding `libgdal` with older versions first? Once `libgdal` is configured without something it can't be added back in (you probably knew this anyway)....

**Comment by gillins** [comment]
I think the system `freexl` is being checked and found to be too old. [Checking for `freexl`](https://trac.osgeo.org/gdal/browser/tags/2.2.3/gdal/configure.ac#L4104) doesn't seem to add the `freexl` lib path. Is it best practice to patch `configure` or `configure.ac` and reconfigure?

**Comment by ocefpaf** [comment]
>  Is it best practice to patch `configure` or `configure.ac` and reconfigure?

I would argue that it is not "best practice" but common practice though in the packaging world. I'll take a look at this tomorrow. 

PS: that system `freexl` is not from homebrew, right? B/c we do remove all homebrew packages :-/

**Comment by ocefpaf** [comment]
> Have you been rebuilding libgdal with older versions first? Once libgdal is configured without something it can't be added back in (you probably knew this anyway)....

No. I created a branch with libgdal + gdal for the tests. See https://github.com/ocefpaf/libgdal-feedstock/tree/test

**Comment by gillins** [comment]
> PS: that system freexl is not from homebrew, right?

Not sure, but it is finding an old one somewhere (see https://travis-ci.org/conda-forge/libgdal-feedstock/builds/306806136#L1461). I'll check on my Mac but no doubt it will be set up differently so I might not learn a lot....

I have found that the `libgdal` `configure` doesn't add `-L$PATHTOLIBDIR` everywhere when running tests, so often picks up the wrong libraries if you have things installed in a "non-standard" way.

**Comment by ocefpaf** [comment]
> Not sure, but it is finding an old one somewhere (see https://travis-ci.org/conda-forge/libgdal-feedstock/builds/306806136#L1461).

Somehow we did not have this problem before, not sure what changed in Travis-CI  :-/
`xcode 7.3` did install `freexl 1.0.2`, but we used that same version before with success.
The new one uses `freexl 1.0.4`, our current one. See https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

Anyway, I'll skip that test on `OS X` for now b/c this is locking tons of updates. We can try to fix it later.

**Pull request merged**
