### PR TITLE
Add patch to avoid substitution of python interpreter in scripts (fixes  #736)

### LINKED ISSUE #736: Confusion of cross-platform Python
The interpreter that's being substituted into the Python-based GDAL utilities like `gdal_edit.py` is cross-python, not the environment's. I suppose this was caused by GDAL changing how it grabbed the active Python environment.

```
mamba create -n gdal363 -c conda-forge gdal=3.6.3 -y
(base) hobu-mbp-14 ~ ~ % mamba activate gdal363
(gdal363) hobu-mbp-14 ~ ~ % gdal_edit.py
zsh: /Users/hobu/miniforge3/envs/gdal363/bin/gdal_edit.py: bad interpreter: /Users/runner/miniforge3/conda-bld/gdal-split_1678794200052/_build_env/venv/bin/cross-python: no such file or directory

```

https://github.com/conda-forge/gdal-feedstock/blob/main/recipe/install_python.sh#L13 doesn't appear to be passing in `CMAKE_ARGS`, so maybe this is the start.

### PR DESCRIPTION
**Pull request by rouault**
This obviously stinks, but no better idea. I can't test locally it works to solve #736 but at least on Linux in my GDAL dev env, it does the job

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
I'm happy with this @rouault - any objections @conda-forge/gdal ?

**Review by akrherz — APPROVED** [review]

**Review by ocefpaf — APPROVED** [review]

**Comment by rouault** [comment]
There's suddenly a strange linking issue
on osx 64:
```
2023-03-20T13:01:35.9843370Z [ 95%] Linking CXX shared library libgdal.dylib
2023-03-20T13:01:36.0909100Z ld: library not found for -lpthreadylib
```
and osx arm64:
```
[ 96%] Linking CXX shared library libgdal.dylib
ld: library not found for -lpthreadbd
```

Comparing quickly the version of the dependencies between the last successfull build (in main) and this PR, I can only see:
```
-libnetcdf:                 4.9.2-nompi_hb6dca1b_100  conda-forge
+libnetcdf:                 4.9.2-nompi_hb6dca1b_101  conda-forge
```
Not sure if that's relevant

**Comment by rouault** [comment]
I also see the same build failure in the GDAL CI master Conda OSX builds. One key difference between last successful builds and erroring one is that icu was updated from 70.1 to 72.1

**Comment by rouault** [comment]
> Same problem...

interestingly removing the explicit libxml2 and icu dependencies didn't prevent them from being pulled (probably through another dependency), but back to icu 70.1. So my hypothesis about icu upgrade doesn't seem to hold.

**Comment by rouault** [comment]
It seems related to HDF5 and duplicated libraries in the HDF5_LIBRARIES variable:
FIND_PACKAGE_MESSAGE_DETAILS_HDF5:INTERNAL=[$PREFIX/lib/libhdf5.dylib;$PREFIX/lib/libcrypto.dylib;$PREFIX/lib/libcurl.dylib;/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.dylib;$PREFIX/lib/libsz.dylib;$PREFIX/lib/libz.dylib;/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libdl.dylib;/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libm.dylib;$PREFIX/lib/libhdf5_cpp.dylib;$PREFIX/lib/libhdf5.dylib;$PREFIX/lib/libcrypto.dylib;$PREFIX/lib/libcurl.dylib;/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.dylib;$PREFIX/lib/libsz.dylib;$PREFIX/lib/libz.dylib;/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libdl.dylib;/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libm.dylib][cfound components: C CXX ][v1.14.0()]

End of linking line with errouenous -lpthreadylib -ldlylib -lmylib

$PREFIX/lib/libhdf5_cpp.dylib $PREFIX/lib/libiconv.dylib $PREFIX/lib/libcrypto.dylib -lm $PREFIX/lib/libmfhdf.dylib $PREFIX/lib/libdf.dylib $PREFIX/lib/libhdf5_hl.dylib  $PREFIX/lib/libhdf5.dylib $PREFIX/lib/libcrypto.dylib $PREFIX/lib/libcurl.dylib -lpthreadylib $PREFIX/lib/libsz.dylib $PREFIX/lib/libz.dylib -ldlylib -lmylib

**Comment by rouault** [comment]
no, HDF5_C_LIBRARIES itself doesn't contain duplicates:
```
  /Users/runner/miniforge3/conda-bld/gdal-split_1679444438080/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libhdf5.dylib
  /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.dylib
  /Users/runner/miniforge3/conda-bld/gdal-split_1679444438080/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libsz.dylib
  /Users/runner/miniforge3/conda-bld/gdal-split_1679444438080/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libz.dylib
  /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libdl.dylib
  /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libm.dylib
```

**Comment by rouault** [comment]
Isn't there some CondaForge magic that messes with paths?  Why does CMakeCache.txt contains things like "$PREFIX/lib/libhdf5.dylib" but the actual path is "/Users/runner/miniforge3/conda-bld/gdal-split_1679444438080/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libhdf5.dylib".
Wouldn't that magic have troubles with paths like "/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.dylib" that it would transform them to -lpthreadylib ? (and -lpthreadbd on osx arm64)

**Comment by gillins** [comment]
> Isn't there some CondaForge magic that messes with paths?

No Idea, @isuruf might know more....

**Comment by isuruf** [comment]
Regex at https://github.com/conda-forge/libnetcdf-feedstock/pull/169 seems wrong

**Comment by rouault** [comment]
Irrelevant debug patches removed from this PR now that the root cause has been spotted

**Comment by xylar** [comment]
I have made and issue for this:
https://github.com/conda-forge/libnetcdf-feedstock/issues/170
But I don't think I have the regex expertise to fix it myself. A PR would be welcome.

**Comment by rouault** [comment]
> A PR would be welcome.

attempt in https://github.com/conda-forge/libnetcdf-feedstock/pull/171

**Comment by rouault** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
After https://github.com/conda-forge/cross-python-feedstock/pull/71 you wouldn't this anymore. You can just do a simple build number bump.

**Comment by rouault** [comment]
superseded per https://github.com/conda-forge/gdal-feedstock/pull/751

**Comment by gillins** [comment]
Thanks @isuruf!

**Pull request closed without merging**
