### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by ocefpaf**
Forgot to do this in #43. (I guess it is time to call it a day and :zzz:)

### CODE REVIEW

**Comment by gillins** [comment]
@ocefpaf what is needed to start new builds of GDAL 2? https://github.com/conda-forge/gdal-feedstock/pull/42 has merged but files haven't appeared on anaconda.org...

**Comment by ocefpaf** [comment]
@gillins you need to bump the build number. Sorry for missing that in your PR. (I was away with a phone and it was hard to read everything.)

PS: I believe we can pin to `jpeg 9b` now. The whole stack seems to the in line with it.

**Comment by gillins** [comment]
Ah. Can't believe I forgot that. I'll make a new PR to pin to 9* and bump the version number.

**Comment by ocefpaf** [comment]
> Ah. Can't believe I forgot that. I'll make a new PR to pin to 9* and bump the build number.

No problem. In fact that was better since now that I (believe) fixed the jpeg pinning. See if you can aling your PR with the changes in https://github.com/conda-forge/gdal-feedstock/pull/43/files for the `build.sh` and `meta.yaml` files.

**Comment by gillins** [comment]
Why are you excluding some drivers for Python 3?

**Comment by ocefpaf** [comment]
> Why are you excluding some drivers for Python 3?

Why am I putting them back :wink:

I downgraded `xz` to `5.0.5` because `xz 5.2.2` did not work with Python 3.4/3.5 so now I can put anu dependency on `xz` back.

**Pull request merged**
