### PR TITLE
Remove zarr

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Just put a static copy of the test data in the recipe (alongside the rest) and use that. This removes a Python library from the dependency tree (where there are almost none already) in order to reduce the set of packages GDAL needs to wait on.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks! folks won't need to wait for https://github.com/conda-forge/numcodecs-feedstock/pull/91 with this change.

**Review by ocefpaf — APPROVED** [review]

**Comment by zklaus** [comment]
To be clear, if I understand correctly, this does *not* remove support for the Zarr format from Gdal (which comes natively), but only removes a dependency on the `zarr` python package which was purely used for testing.

**Comment by akrherz** [comment]
> To be clear, if I understand correctly, this does _not_ remove support for the Zarr format from Gdal (which comes natively), but only removes a dependency on the `zarr` python package which was purely used for testing.

That is my understanding!

**Comment by ocefpaf** [comment]
Yep. Correct. That test dependency was blocking the Python 3 migration and we don't really need it, just the data for testing.

**Pull request merged**
