### PR TITLE
Use libkml-devel

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akrherz** [comment]
Just to denote some motivation for this conda-forge/libkml-feedstock#28

> This separates the headers into a libkml-devel output which has the libboost-headers dependency. Therefore downstream  packages like gdal will not be pulling in the heavy libboost-headers dependency that takes forever to install on windows.

`libkml` is in pinning though, doesn't it need updated / rerendered?

**Comment by isuruf** [comment]
Added in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6138

**Comment by akrherz** [comment]
Doesn't this need rerendered though?

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Review by akrherz — APPROVED** [review]

**Pull request merged**
