### PR TITLE
Revert #629

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

reverting #629 and bumping build to 3 as 2 will be marked bad.

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
OK, I think I got this is good shape now.  Can somebody else here sign off on this?

**Comment by xylar** [comment]
@akrherz, I think these could just be one commit unless there's a specific reason to revert them one by one.

**Comment by akrherz** [comment]
@xylar shrug, I see I got a transient build failure due to the tqdm troubles, so will squash as you suggest...

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
I have also submitted conda-forge/admin-requests#489 to denote build 2 as broken.  Hopefully between these two, we can get things cleaned up asap.

@xylar you good with this now?

**Review by xylar — APPROVED** [review]

**Review by gillins — APPROVED** [review]

**Pull request merged**
