### PR TITLE
Link with setargv on Windows

### LINKED ISSUE #558: Enable wildcard expansion on Windows
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

In the conda-forge build of GDAL, programs currently do not perform command-line wildcard expansion on Windows, unlike e.g. the OSGeo4W builds. This different behavior may be confusing to users and break certain scripts. Example:

```
> gdalbuildvrt combined.vrt *.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 4: `*.tif' does not exist in the file system, and is not recognized as a supported dataset name.
Warning 1: Can't open *.tif. Skipping it
```

On Windows, wildcard expansion (e.g. `*.tif` to `a.tif b.tif c.tif`) is not performed by the shell, unlike on *nix. However, programs may opt in to performing wildcard expansion themselves by [having them linked](https://docs.microsoft.com/en-us/cpp/c-language/expanding-wildcard-arguments) with `setargv.obj`/`wsetargv.obj` at build time.

I am not sure whether it is desirable to add command-line wildcard test cases to GDAL itself, but it seems relevant to make a decision here one way or another.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\[OMITTED]\AppData\Local\Continuum\miniconda3\envs\gdal:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.74.0               h5b4e17d_5    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cairo                     1.16.0            h15b3021_1009    conda-forge
cfitsio                   4.0.0                hd67004f_0    conda-forge
curl                      7.79.1               h789b8ee_1    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
gdal                      3.3.3            py38h117dad8_3    conda-forge
geos                      3.10.0               h39d44d4_0    conda-forge
geotiff                   1.7.0                h350af67_3    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
git                       2.33.1               h57928b3_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_101    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
kealib                    1.4.14               h8995ca9_3    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libffi                    3.4.2                h0e60522_4    conda-forge
libgdal                   3.3.3                h6357ee8_3    conda-forge
libglib                   2.70.0               h3be07f2_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_3    conda-forge
librttopo                 1.1.0                h22ffb85_7    conda-forge
libspatialite             5.0.1               h9c61790_10    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
numpy                     1.21.4           py38h089cfbf_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   21.09.0              h24fffdf_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.3                 h1c22c4f_3    conda-forge
proj                      8.1.1                h1cfcee9_2    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
setuptools                58.5.3           py38haa244fe_0    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
tbb                       2021.4.0             h2d74725_1    conda-forge
tiledb                    2.3.4                h78dabda_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.3                h0e60522_4    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : gdal
    active env location : C:\Users\[OMITTED]\AppData\Local\Continuum\miniconda3\envs\gdal
            shell level : 2
       user config file : C:\Users\[OMITTED]\.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.7.11.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\[OMITTED]\AppData\Local\Continuum\miniconda3  (writable)
      conda av data dir : C:\Users\[OMITTED]\AppData\Local\Continuum\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\[OMITTED]\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\[OMITTED]\.conda\pkgs
                          C:\Users\[OMITTED]\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\[OMITTED]\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\[OMITTED]\.conda\envs
                          C:\Users\[OMITTED]\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.7.11 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


```
</details>

### PR DESCRIPTION
**Pull request by plimkilde**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Link with `setargv` on Windows to enable wildcard expansion. ~~WIP to see how it builds in CI.~~

Closes #558

### CODE REVIEW

**Comment by gillins** [comment]
Hmm I wonder if `SETARGV` needs to be doubly quoted like OSGeo4W does (https://github.com/jef-n/OSGeo4W/blob/master/src/gdal/osgeo4w/package.sh#L139)?

**Comment by plimkilde** [comment]
I can't think of any remaining issues here, let me know if further changes are needed.

**Review by akrherz — APPROVED** [review]
I have no windows expertise, but this seems in order.

**Comment by ocefpaf** [comment]
> I have no windows expertise, but this seems in order.

Same. I defer to @gillins, sorry :grimacing:

**Comment by gillins** [comment]
Thanks @plimkilde !

**Comment by plimkilde** [comment]
Awesome, thank you very much for your guidance @gillins !

**Comment by ocefpaf** [comment]
Thank you both for improving the Windows experience!

**Pull request merged**
