### PR TITLE
v2.3.3

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
Please merge #250 before handling this new version.

**Comment by kmuehlbauer** [comment]
Örks, need to revisit patches.

**Comment by kmuehlbauer** [comment]
@ocefpaf Locally patching complains about different line endings. Do we need the windows patches under linux? Can we skip it via meta.yaml?

**Comment by ocefpaf** [comment]
> @ocefpaf Locally patching complains about different line endings. Do we need the windows patches under linux? Can we skip it via meta.yaml?

Ideally we should apply patches that are upstreamable to all platforms and, well, upstream them :-) But b/c we never made the effort to do so we can probably skip those for now.

**Pull request merged**
