### PR TITLE
Remove build: skip to enable later libarrow versions (cont'd)

### PR DESCRIPTION
**Pull request by rouault**
Add extra commit to https://github.com/conda-forge/gdal-feedstock/pull/805

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks, if this works, we'd still need the build number bumped.

**Comment by jorisvandenbossche** [comment]
This worked! Thanks Even

**Comment by kylebarron** [comment]
Awesome, thanks!

**Review by akrherz — APPROVED** [review]

**Comment by akrherz** [comment]
closes #797

**Pull request merged**
