### PR TITLE
remove symlinks

### PR DESCRIPTION
**Pull request by gillins**
I forgot to unpin `conda-build` when using `toolchain` which means symlinks get left in. This should fix it.

cc @jakirkham

### CODE REVIEW

**Comment by jakirkham** [comment]
So, this is pretty weird. When I grabbed `osx-64/gdal-2.1.0-np111py35_6.tar.bz2`, it looked fine. Now there are 6 packages. Thus maybe some of them are broken, but it is strange that this one wasn't. 😕

**Comment by jakirkham** [comment]
Could you please let me know which ones are broken, @gillins, and I will mark them as broken?

**Comment by gillins** [comment]
You are right - the latest one (with `toolchain` is fine). Very strange.

Maybe I should remove the build number bump?

**Comment by jakirkham** [comment]
Were all of the OS X build number 6 packages fine?

**Comment by gillins** [comment]
Yes

**Comment by jakirkham** [comment]
😳 Weird. It would be nice if we could narrow down the cause for this change. Maybe it will be easier with `libtiff`? There was a recent `conda` release. So this behavior may have changed with it.

**Comment by gillins** [comment]
Should I close this, and leave it as it was? I'm guessing the next change to `conda-smithy` will update anything that needs to be changed?

**Comment by jakirkham** [comment]
Not sure. In one sense, it isn't a problem here. In the other, we don't really know why it is not a problem or whether it will return. I'd lean towards unpinning because we know that works and why. Though I guess the build number change is optional.

**Comment by gillins** [comment]
Turned out that this package wasn't broken like `hdf5` etc so a rebuild and new version isn't required, but good to have it unpinned in case there is a problem in the future.

**Pull request merged**
