### PR TITLE
Rebuild with icu69 openssl3 libpq

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This reverts the changes from the #590 intermediate build in support of my never-ending quest on #585.

### CODE REVIEW

**Comment by akrherz** [comment]
The diff here between this and prior to the intermediate build is just a change with the DOCKER image (plus build number bump)

```diff
$ git diff 4c5b62c0..f55a86e
diff --git a/.azure-pipelines/azure-pipelines-linux.yml b/.azure-pipelines/azure-pipelines-linux.yml
index fd96606..caa7a50 100755
--- a/.azure-pipelines/azure-pipelines-linux.yml
+++ b/.azure-pipelines/azure-pipelines-linux.yml
@@ -11,27 +11,27 @@ jobs:
       linux_64_openssl1.1.1:
         CONFIG: linux_64_openssl1.1.1
         UPLOAD_PACKAGES: 'True'
-        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
+        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
....and so on....
```

This just a transient mamba issue?

**Comment by xylar** [comment]
@akrherz, I'd suggest pinging someone from core or posting something on https://gitter.im/conda-forge/conda-forge.github.io to see if this is a known issue.  I haven't seen anything about it.

**Comment by xylar** [comment]
The openssl issue did, indeed, seem to fix itself.

**Comment by akrherz** [comment]
Thanks for checking @xylar!  Reviewing the logs, the failed build ran with mamba 0.15.3 and the successful ran with 0.18.2.

**Comment by xylar** [comment]
Ah, I wondered about that.  A mamba upgrade certainly would explain why it worked for me.

**Pull request merged**
