### PR TITLE
Add a separate script for windows python build

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I'm hoping this will fix the Win build problems we've seen in several other PRs.  I'm guessing (but not at all sure) that something about the build system changed and bash scripts are behaving strangely under Win.

**Comment by ocefpaf** [comment]
Thanks @xylar. I wonder if we should report this upstream. Looks like a regression in conda-build, no?

**Comment by xylar** [comment]
> I wonder if we should report this upstream.

I don't understand enough about where to report this or what the problem is.  If you feel like you understand it, I think that would be great!

**Pull request merged**
