### PR TITLE
features

### PR DESCRIPTION
**Pull request by ocefpaf**
Note to self: If this works here do the same for `gdal2` branch.

### CODE REVIEW

**Comment by pelson** [comment]
I tried implementing multibranch MNT PRs on this feedstock at #14 and #15. Happy for them to be ignored, but I'm getting close to having the necessary tools for multibranch support. :+1:

**Comment by ocefpaf** [comment]
Ah got it now.

**Comment by ocefpaf** [comment]
The thing is that #13 also add features, which is not handled automatically, right?

**Comment by pelson** [comment]
> The thing is that #13 also add features, which is not handled automatically, right?

Right. The manual approach is the only way when you want to make functional changes (I can't script that bit out :wink:)

**Comment by ocefpaf** [comment]
> Right. The manual approach is the only way when you want to make functional changes (I can't script that bit out :wink:)

:relieved: I am not completely obsolete!

**Pull request merged**
