### PR TITLE
Drop v3.1.x and v3.2.x from abi_migration_branches

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #532
closes #528
closes #526
closes #487
closes #491

### CODE REVIEW

**Comment by xylar** [comment]
I would like to propose that we drop `v3.1.x` from migration.  It seems like we're basically pretty stuck anyway and the conda-forge pin has been 3.2 for awhile and 3.3 migration seems to basically be done (https://conda-forge.org/status) with only a few neglected packages still remaining.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
:+1: @xylar - I think this is a great idea! I wonder if we can remove 3.2.x also? Can you easily tell if there is software still pinned against 3.2.x?

**Comment by xylar** [comment]
@gillins, I think it might still be best to keep migrating `v3.2.x` until the pin is officially update on `conda-forge-pinning`.  But I'll be happy to drop it if @ocefpaf things it's time.

**Comment by xylar** [comment]
@ocefpaf, I'd like your approval before I make this change.  Let me know what you think.  I just rebased so CI will presumably take ages to finish.  But I didn't bump the build number because there's no need for new packages.  So I don't think we necessarily need to wait for CI to complete in this particular case.

**Review by ocefpaf — APPROVED** [review]

**Comment by ocefpaf** [comment]
Usually `rasterio` is the last package to "catch up" with gdal releases. If that one can be build and all the tests passes with 3.3 I'm OK dropping 3.2 as well.

**Comment by xylar** [comment]
Great, thanks!

**Comment by xylar** [comment]
Yes, rasterio got updated in https://github.com/conda-forge/rasterio-feedstock/pull/207, so I think we could also drop 3.2.  I'll do that now in this PR.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
As I said, I'm not going to wait for CI on this one because I'm not bumping the build number.

**Pull request merged**
