### PR TITLE
rebuild with proj 8.2.0 (3.3 branch)

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This rebuilds with proj 8.2.0 on the 3.3.x branch of GDAL.

closes #565

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin restart ci

A missing geotiff build for aarch64 is available now, crosses fingers.

**Comment by akrherz** [comment]
The `linux_ppc64le_` job from the prior to restart just now got cancelled and seemed to foul up the rerun.  the build so far on the other platforms looks in good shape.

@conda-forge-admin restart ci

**Comment by akrherz** [comment]
sigh, trying cycle again

@conda-forge-admin restart ci

**Comment by akrherz** [comment]
The Azure UI is more promising than the Github UI is that these builds are running now.  Tempting fate with the `automerge` tag now as this should work.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please restart ci

**Comment by xylar** [comment]
I apologize for restarting again.  I didn't realize that Azure was actually running despite the error message here.  I'll try to keep an eye on it: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=408334&view=results

**Pull request merged**
