### PR TITLE
update/fix deps per #690

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This brings the dep fixes from #690 to the v3.4.x branch, of which my heavy env is still stuck with, sigh...

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
Well, this is depressing.  I wonder if main branch can even be dep solved now... trying...

**Comment by akrherz** [comment]
rerendering is getting a strange combo of hdf5=1.12.1 cfitsio=4.1.0 and tiledb=2.11  , boggling

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
Sweet, a green PR for @conda-forge/gdal to consider.  I can cleanup the git history or we can just leave it as this is a legacy branch anyway.

**Review by ocefpaf — APPROVED** [review]

**Comment by ocefpaf** [comment]
> I can cleanup the git history or we can just leave it as this is a legacy branch anyway.

I would leave it but I'll let you decide on what is easier for you here.

**Pull request merged**
