### PR TITLE
[3.6.x] Fix deactivate.sh

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Same here, feel free to merge once CI finishes unless there's another typo I missed.

**Comment by rouault** [comment]
Aren't those scripts tested by CI ?
Perhaps a ``set -eu`` would be needed in them ?

**Comment by xylar** [comment]
@rouault, I'm not sure about a `set -eu`.  That's certainly not a standard practice on conda-forge and I thought I had the sense that was a bad idea when you source a script as opposed to run it.

> Aren't those scripts tested by CI ?

The activate scripts are certainly tested.  The deactivate scripts maybe not or any errors they produce may simply be ignored, not sure about that.  I guess that's where your `set -eu` would come in.  I'll leave it to folks with more shell knowledge to decide if that can be added.

**Comment by xylar** [comment]
So looking into this further, I do think `set -eu` in a sourced script will cause the shell to exit completely when there's an error, see https://stackoverflow.com/a/24460931/7728169.  So it doesn't seem like that's something we can add.

Anyone have any other input on this?  Otherwise, I'd like to merge soon because this bug is likely to break deactivation for folks using the latest gdal.

**Comment by rouault** [comment]
> Anyone have any other input on this?

Please merge the fix. And thanks for your valid points on why set -eu wouldn't be appropriate

**Comment by xylar** [comment]
Thanks @rouault

**Pull request merged**
