### PR TITLE
Rebuild v3.6.2 with proj 9.1.0

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Pyproj isn't compatible with proj 9.1.1 (see https://github.com/conda-forge/pyproj-feedstock/issues/126) and this is causing trouble for downstream packages.  Let's undo the migration to proj 9.1.1 (at least for one build).

**Comment by xylar** [comment]
@conda-forge/gdal, any objections to this?

**Review by ocefpaf — APPROVED** [review]

**Review by akrherz — APPROVED** [review]

**Comment by gillins** [comment]
Thanks @xylar !

**Pull request merged**
