### PR TITLE
Pin to libnetcdf 4.4

### PR DESCRIPTION
**Pull request by ocefpaf**
Needs https://github.com/conda-forge/libnetcdf-feedstock/pull/1.

Note to self: if this works port it to `gdal 2`.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Windows is failing with the latest `libnetcdf`. Any ideas of what may be going on @gillins?

**Comment by pelson** [comment]
Because google is great, it is worth posting the traceback IMO :smile::

```
nitf_gcprpc.obj : warning LNK4221: no public symbols found; archive member will be inaccessible
cpl_recode_iconv.obj : warning LNK4221: no public symbols found; archive member will be inaccessible
	link /nologo /dll /INCLUDE:_OGRFeatureStylePuller  /INCLUDE:_OSRValidate  /INCLUDE:_OPTGetProjectionMethods  /INCLUDE:_OGR_G_GetPointCount  /INCLUDE:_OGRRegisterAll /INCLUDE:_GDALSimpleImageWarp@36  /INCLUDE:_GDALReprojectImage@48  /INCLUDE:_GDALComputeMedianCutPCT@32  /INCLUDE:_GDALDitherRGB2PCT@28  /INCLUDE:_OCTNewCoordinateTransformation@8  port\*.obj gcore\*.obj alg\*.obj frmts\o\*.obj ogr\ogrsf_frmts\ogrsf_frmts.lib ogr\ogr.lib    C:\conda\envs\_build\Library\lib\xerces-c_3.lib           C:\conda\envs\_build\Library\lib\libjpeg.lib C:\conda\envs\_build\Library\lib\netcdf.lib    C:\conda\envs\_build\Library\lib\libtiff_i.lib C:\conda\envs\_build\Library\lib\proj.lib    C:\conda\envs\_build\Library\lib\geos_c.lib C:\conda\envs\_build\Library\lib\hdf5.lib      C:\conda\envs\_build\Library\lib\libcurl.lib wsock32.lib wldap32.lib winmm.lib     odbc32.lib odbccp32.lib user32.lib  C:\conda\envs\_build\Library\lib\libpng.lib  C:\conda\envs\_build\Library\lib\openjp2.lib                  ws2_32.lib gcore\Version.res  /out:gdal111.dll /implib:gdal_i.lib   
   Creating library gdal_i.lib and object gdal_i.exp
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_DOUBLE_g referenced in function "bool __cdecl GH5_FetchAttribute(int,char const *,double &,bool)" (?GH5_FetchAttribute@@YA_NHPBDAAN_N@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_DOUBLE_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_FLOAT_g referenced in function "bool __cdecl GH5_FetchAttribute(int,char const *,double &,bool)" (?GH5_FetchAttribute@@YA_NHPBDAAN_N@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_FLOAT_g
hdf5imagedataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_FLOAT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_INT_g referenced in function "bool __cdecl GH5_FetchAttribute(int,char const *,double &,bool)" (?GH5_FetchAttribute@@YA_NHPBDAAN_N@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_INT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_ULLONG_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_ULLONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_LLONG_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_LLONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_ULONG_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_ULONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_LONG_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_LONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_UINT_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_UINT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_USHORT_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_USHORT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_SHORT_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_SHORT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_UCHAR_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_UCHAR_g
gh5_convenience.obj : error LNK2019: unresolved external symbol _H5T_NATIVE_SCHAR_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol _H5T_NATIVE_SCHAR_g
gdal111.dll : fatal error LNK1120: 12 unresolved externals
NMAKE : fatal error U1077: '"C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.EXE"' : return code '0x460'
Stop.
Command failed: C:\Windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Comment by gillins** [comment]
I think this is the same problem: https://github.com/conda-forge/gdal-feedstock/issues/25

I'll check and submit a PR shortly.

**Comment by gillins** [comment]
See https://github.com/ocefpaf/gdal-feedstock/pull/1. Seems to build for me now.

**Comment by ocefpaf** [comment]
Thanks to @gillins magical Windows tough the builds are passing again!

**Pull request merged**
