### PR TITLE
Update to GDAL 3.9.0

### LINKED ISSUE #857: Memo for GDAL 3.9
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

- Now that https://gdal.org/development/rfc/rfc96_deferred_plugin_loading.html has been merged into GDAL master 3.9dev, the following change will have to be done in gdal-feedstock when updating to 3.9:
https://github.com/OSGeo/gdal/commit/b494ada1c6c7366f041950052f2f6b553d357ad1

- And for python bindings: https://github.com/OSGeo/gdal/pull/8926/commits/442b785c8f90342c0472caf16348737d4e1b2f98

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

### PR DESCRIPTION
**Pull request by rouault**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #857

We probably don't want to get this merged before final 3.9.0, but this is a way of checking everything is fine

### CODE REVIEW

**Comment by rouault** [comment]
@conda-forge-admin, please rerender

**Comment by rouault** [comment]
@conda-forge-admin, please rerender

**Comment by rouault** [comment]
This is ready for review

**Comment by akrherz** [comment]
Thank you @rouault for this!  I took the liberty to bump abi_migration_branches to `v3.8.x` with this PR too

**Comment by akrherz** [comment]
So, I would like suggest sneaking PR #920 in first, so that main branch is ready to be branched to `v3.8.x` and then taking this PR.

**Review by akrherz — APPROVED** [review]

**Comment by akrherz** [comment]
`v3.8.x` branch created and automerge set on this PR, should be good to go!

**Comment by akrherz** [comment]
oye, arm-osx failure seems transient / unrelated.  Will try restarting the job

```
WARNING: The cross-compiler ('arm64-apple-darwin20.0.0-clang') does not appear to be for the correct architecture (got arm64-apple-darwin20.0.0, expected aarch64-apple-darwin20.0.0). Use --cc to correct, if necessary.
dyld[72031]: Library not loaded: '@rpath/libpopt.0.dylib'
  Referenced from: '/Users/runner/miniforge3/pkgs/rsync-3.3.0-h5aaac6a_0/bin/rsync'
  Reason: tried: '/Users/runner/miniforge3/pkgs/rsync-3.3.0-h5aaac6a_0/bin/../lib/libpopt.0.dylib' (no such file), '/Users/runner/miniforge3/pkgs/rsync-3.3.0-h5aaac6a_0/bin/../lib/libpopt.0.dylib' (no such file), '/usr/local/lib/libpopt.0.dylib' (no such file), '/usr/lib/libpopt.0.dylib' (no such file)
/Users/runner/miniforge3/conda-bld/gdal-split_1715426344365/_build_env/etc/conda/activate.d/activate_z-cross-python_osx-arm64.sh: line 104: 72031 Abort trap: 6           rsync -a --exclude="*.so" --exclude="*.dylib" -I $PREFIX/lib/python$PY_VER/site-packages/ $BUILD_PREFIX/lib/python$PY_VER/site-packages/
```

**Pull request merged**
