### PR TITLE
update deps per #690

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Addresses #690 for v3.5.x branch.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
I do notice that the builds are getting `pcre=10.37` pins as I suspect the dep solver has some issue getting `10.40`.

I believe this PR is ready to go otherwise as I am not finding the link errors reported anymore in the build logs.

**Comment by xylar** [comment]
> I do notice that the builds are getting pcre2=10.37 pins as I suspect the dep solver has some issue getting 10.40.

@akrherz, unless you manually add the migrator, that's to be expected.
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/pcre21040.yaml

**Comment by xylar** [comment]
After you merge this, I would expect there to be a bot PR to migrate to pcre2=10.40.

**Comment by akrherz** [comment]
Thanks @xylar , I followup this PR with the migrator, so then we can have builds matching both versions...

**Pull request merged**
