### PR TITLE
Update to 1.11.5

### PR DESCRIPTION
**Pull request by ocefpaf**
- update to latest version of `gdal 1.x` series.
- add `libdap` support
- synced with master changes and updates

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins I remove `sqlite` (and `spatilite`) from `gdal 1.11.5` on Windows (from commit https://github.com/conda-forge/gdal-feedstock/pull/97/commits/42d29f344242a6edcd99e75635bd6b71b8ac5533). I am getting the error below. Any advice? (Note this is very low priority as everything is smooth now with `gdal 2.x`.)


```shell
	cl   /nologo /MD /EHsc /Ox /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /DNDEBUG /W4 /wd4127 /wd4251 /wd4275 /wd4786 /wd4100 /wd4245 /wd4206 /wd4018 /wd4389 /DHAVE_SSE_AT_COMPILE_TIME -I..\..\..\port -I..\..\..\ogr -I..\..\..\gcore  -I..\..\..\alg -I..\..\..\ogr\ogrsf_frmts -I.. -I..\.. -IC:\conda\envs\_build\Library\include -DHAVE_SPATIALITE   -DSPATIALITE_412_OR_LATER -DOGR_ENABLED  /c ogrsqlitedriver.cpp ogrsqlitedatasource.cpp ogrsqlitelayer.cpp ogrsqlitetablelayer.cpp ogrsqliteviewlayer.cpp ogrsqliteselectlayer.cpp ogrsqlitesinglefeaturelayer.cpp ogrsqlitevfs.cpp ogrsqlitevirtualogr.cpp ogrsqliteexecutesql.cpp 
ogrsqlitedriver.cpp
ogrsqlitedatasource.cpp
ogrsqlitelayer.cpp
ogrsqlitelayer.cpp(568) : warning C4244: 'argument' : conversion from 'sqlite3_int64' to 'long', possible loss of data
ogrsqlitetablelayer.cpp
ogrsqlitetablelayer.cpp(738) : warning C4244: 'return' : conversion from 'GIntBig' to 'int', possible loss of data
ogrsqliteviewlayer.cpp
ogrsqliteselectlayer.cpp
ogrsqlitesinglefeaturelayer.cpp
ogrsqlitevfs.cpp
ogrsqlitevirtualogr.cpp
ogrsqlitevirtualogr.cpp(63) : fatal error C1083: Cannot open include file: 'sqlite3ext.h': No such file or directory
ogrsqliteexecutesql.cpp
ogrsqliteexecutesql.cpp(780) : warning C4244: 'argument' : conversion from 'vsi_l_offset' to 'size_t', possible loss of data
ogrsqliteexecutesql.cpp(786) : warning C4244: 'argument' : conversion from 'vsi_l_offset' to 'size_t', possible loss of data
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'for' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.EXE"' : return code '0x2'
Stop.
Command failed: C:\windows\system32\cmd.exe /c bld.bat
```

**Comment by gillins** [comment]
GDAL 2.x has the `SQLITE_INC`, `SQLITE_LIB`, `SPATIALITE_412_OR_LATER` etc build variables set. Maybe these should be added to 1.x to be consistent?

I don't know it doesn't work without this anyway...

**Comment by ocefpaf** [comment]
> GDAL 2.x has the `SQLITE_INC`, `SQLITE_LIB`, `SPATIALITE_412_OR_LATER`

Are you referring to the `bld.bat` `cmake` call? I had those in https://github.com/conda-forge/gdal-feedstock/pull/97/commits/42d29f344242a6edcd99e75635bd6b71b8ac5533 and it did not work.

See https://github.com/conda-forge/gdal-feedstock/pull/97/commits/42d29f344242a6edcd99e75635bd6b71b8ac5533#diff-d04c86b6bb20341f5f7c53165501a393R71

**Comment by gillins** [comment]
Sorry @ocefpaf I don't think I read your first message properly. You mean that with `sqlite` GDAL 1.11.5 didn't build? Seems to make sense looking at the differences with 2.1 (https://trac.osgeo.org/gdal/browser/branches/1.11/gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp vs https://trac.osgeo.org/gdal/browser/branches/2.1/gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp). 

`conda-forge` `sqlite` doesn't come with `sqlite3ext.h` and GDAL 2.1 doesn't include it. Seems a bug in GDAL 1.11.5?

**Comment by ocefpaf** [comment]
> `conda-forge` `sqlite` doesn't come with `sqlite3ext.h` and GDAL 2.1 doesn't include it. Seems a bug in GDAL 1.11.5?

Thanks @gillins. Since this is kind of low priority (I don't believe there is a lot of people relaying on `gdal 1.x`) I merged this without `sqlite`. I will open an issue to keep track of it though.

**Pull request merged**
