### PR TITLE
Switch gdal2 to master with gdal 2.1.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf Do you need anything more from my side to merge this into master?

**Comment by ocefpaf** [comment]
There are conflicts all over. Not sure how you sent the PR, but I check out a fresh `master`, copy the `gdal` file over, and submit the PR. Maybe, to preserve the history that is a bad idea... Hold on. Let me try  something first.

**Comment by ocefpaf** [comment]
@kmuehlbauer there are no conflicts now since `master` is now the `gdal2` branch. However, even though this is merge-able, there are some weird commits in the history. Are you OK closing this and re-sending? I think this will be the last time :wink:

**Comment by kmuehlbauer** [comment]
I'm not sure what went wrong, but I can resend.

**Comment by ocefpaf** [comment]
> I'm not sure what went wrong, but I can resend.

It was not you. I changed the master to be `gdal2`, so the extra commits are already here. As you can see they don't appear in #50.

PS: I will delete the `gdal2` once @gillins is up-to-date with the changes here.

**Pull request closed without merging**
