### PR TITLE
Rebuild for lz4_c 1.10, swap xz for liblzma

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

picks up where #1022 left off.  The bot appears to be having timeout errors attempting to generate it.  The rerendering is taking 12-15 minutes even...
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
Punting on `xz` change for now.

**Comment by akrherz** [comment]
> The "fix" would probably to have liblzma-devel has a build depedency of all plugins

Thank you, that was my conclusion as well, but I didn't have much confidence in it.  Will create an issue for this and come with a dedicated PR for it.

**Comment by akrherz** [comment]
> For some reason, core files are rebuilt.

This seems to be a different problem that really causes our build time to explode.  Will create an issue for it as well :)

**Comment by akrherz** [comment]
Goodness, same `lzma.h` error.  We must have been getting `xz` before in a transient manner and we were getting lucky...  Will bring the liblzma-devel change here now

**Comment by akrherz** [comment]
- [ ] check that there are no linking warnings with this for libgdal-core.

**Comment by akrherz** [comment]
Yeah, will address this prior to merging, for example

> WARNING (libgdal-fits): run-exports library package conda-forge/linux-64::liblzma==5.6.3=hb9d3cd8_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)

**Comment by rouault** [comment]
cf https://github.com/conda-forge/gdal-feedstock/issues/1027#issuecomment-2537661848 / https://github.com/conda-forge/freexl-feedstock/pull/31 for the likely reason & temptative fix for the minizip related failure on Windows

**Comment by akrherz** [comment]
heaven help us, hopefully transient osx build failure, but has happened twice now...

```
llvm-otool', '-l', '/Users/runner/miniforge3/conda-bld/libgdal-core_1734003437752/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/gdalplugins/ogr_PG.dylib']' died with <Signals.SIGABRT: 6>
```

**Comment by rouault** [comment]
The osx arm64 build in master crashed again... : https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1107495&view=logs&j=d6b58996-039f-5e48-56bf-c3a016e5cd7f&t=dd6a23d9-2356-5264-64bf-579875a5d8d6

**Pull request merged**
