### PR TITLE
Cleanup requirements

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This adds sysroot to libgdal in order to create the necessary runtime dependency on `__glibc >=2.17`.
This addresses #606 for future builds, but still, a repo patch is needed for existing builds.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
very cool, cheers @zklaus :beer:

**Review by xylar — APPROVED** [review]
Looks good!

**Review by akrherz — APPROVED** [review]
Thank you!

**Comment by ocefpaf** [comment]
> Cheers guys! Feel free to merge (I am not a maintainer).

Consider adding yourself as a maintainer. Gdal is one of the hardest packages we maintain in conda-forge and your help is greatly appreciated!

**Comment by valeriupredoi** [comment]
well done @zklaus and cheers for the input @ocefpaf - can I also get a virtual :beer: for raising this please :grin:

**Comment by zklaus** [comment]
Here you go, @valeriupredoi: :beers:

**Pull request merged**
